[pytest]
testpaths = tests
addopts = -v
pythonpath = .
filterwarnings =
    ignore:.*iscoroutinefunction.*:DeprecationWarning
    ignore:.*get_event_loop_policy.*:DeprecationWarning
    ignore:.*utcnow.*:DeprecationWarning
env =
    CELERY_TASK_ALWAYS_EAGER=true